export type StatsTableKey = "sessions" | "visits" | "referrals" | "events";
export type SortDir = "asc" | "desc";

export const tableColumns = {
  sessions: [
    "session_id",
    "visitor_id",
    "visit_count",
    "event_count",
    "minutes_spent",
    "referral_code",
    "country",
    "first_seen_at",
    "last_seen_at",
  ],
  visits: [
    "id",
    "created_at",
    "visitor_id",
    "session_id",
    "referral_code",
    "path",
    "full_url",
    "referrer",
    "method",
    "user_agent",
    "ip_address",
    "country",
    "region",
    "city",
    "latitude",
    "longitude",
    "timezone",
    "query_string",
  ],
  referrals: [
    "code",
    "referrer_name",
    "created_at",
    "created_by_visitor_id",
    "created_by_session_id",
    "created_ip",
    "created_country",
    "created_region",
    "created_city",
    "created_user_agent",
    "source",
  ],
  events: [
    "id",
    "created_at",
    "event_name",
    "event_location",
    "href",
    "path",
    "full_url",
    "referrer",
    "visitor_id",
    "session_id",
    "referral_code",
    "user_agent",
    "ip_address",
    "country",
    "region",
    "city",
    "timezone",
    "metadata",
  ],
} as const satisfies Record<StatsTableKey, readonly string[]>;

export const tableDefaults = {
  sessions: { sortBy: "visit_count", sortDir: "desc" as SortDir },
  visits: { sortBy: "created_at", sortDir: "desc" as SortDir },
  referrals: { sortBy: "created_at", sortDir: "desc" as SortDir },
  events: { sortBy: "created_at", sortDir: "desc" as SortDir },
} as const;

